scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8888']
      - targets: ['otel-collector:8889']

  - job_name: 'service-a-cep'
    scrape_interval: 10s
    static_configs:
      - targets: ['service-a-cep:8081']

  - job_name: 'service-b-climate'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'service-b-climate:8082' ]